### ISSUE TITLE
[FEATURE] : Bottom to Top Button for mobile devices

### ISSUE THREAD

**Issue by SrinivasDevolper** [singhJasvinder101/MyBlog#100]
### Feature Description

Bottom to Top Button on mobile devices for user-freindly

### Use Case

User-Friendly

### Potential Solution

User-Friendly

### Additional Context

![upscroll button](https://github.com/singhJasvinder101/MyBlog/assets/121508628/c5a8a6a2-f84b-4e90-864f-4bf71fc94902)

**I am GSSOC24 Contributor
Please assign me, would like to work on it**

**Comment by singhJasvinder101** [comment]
Issue #80  issue already opened similar to this issue so marking this as duplicate you can contribute there
