### ISSUE TITLE
[FEATURE] Strong Password

### ISSUE THREAD

**Issue by SrinivasDevolper** [singhJasvinder101/MyBlog#101]
### Feature Description

Strong Password

### Use Case

password secure

### Potential Solution

Strong Password

### Additional Context

Like This

![string password](https://github.com/singhJasvinder101/MyBlog/assets/121508628/ff5f265d-6106-43c2-9c7f-f14246b10890)

**I am GSSOC24 Contributor
Please assign me, I would like to work on it**

**Comment by singhJasvinder101** [comment]
Someone has already created pull request for this issue and working on it.
