### ISSUE TITLE
[FEATURE] Search bar

### ISSUE THREAD

**Issue by MadhurimaNayak** [singhJasvinder101/MyBlog#106]
### Feature Description

Implementing a search bar to help users search for articles using particular keywords

### Use Case

The user has to manually scroll through the articles searching for the topic of their interest.

### Potential Solution

A search bar would allow user to get articles related to their topic on the click of a button.

**Comment by singhJasvinder101** [comment]
search bar already present to search the blogs via text, tags or headings.

**Comment by MadhurimaNayak** [comment]
okay, but it doesn't seem to be working:

https://github.com/singhJasvinder101/MyBlog/assets/124715194/673fff7d-c80e-4295-8051-7b1cd5fed6d8

**Comment by singhJasvinder101** [comment]
The user need to be authenticated for using searching of posts functionality.

**Comment by MadhurimaNayak** [comment]
Isn't it better if users can search without having to log in? Because a newcomer will likely think that this function is not working.
