### ISSUE TITLE
Display the pop up messages for form handling messages by using react-toastify

### ISSUE THREAD

**Issue by ankitgupta143** [singhJasvinder101/MyBlog#108]
### Feature Description

Pop-up messages for handling form validation

### Use Case

I can add feature in all authentication page like when user create a account it display the pop-up messages like User created successfully, similarly for other also. Also handle the form validation. By adding this feature, website look perfect.

### Potential Solution

I can add by using react-toastify packages

**Comment by singhJasvinder101** [comment]
No need for using react toastify the error in red coloured label is showing below
