### ISSUE TITLE
[FEATURE] Enable Custom Workflows for Task Automation

### ISSUE THREAD

**Issue by thevijayshankersharma** [singhJasvinder101/MyBlog#109]
### Feature Description

I am requesting the ability to create custom workflows within our project management system. These workflows would allow users to automate task transitions, notifications, and actions based on predefined conditions and triggers.

### Use Case

Currently, our team manually moves tasks through various stages of our project management process. This manual process is time-consuming and prone to errors, such as forgetting to notify stakeholders or update statuses. With custom workflows, we could automate these transitions. For example, when a task is marked as "In Progress," automatically notify the assigned team members. When a task is marked as "Complete," update related documentation and notify project stakeholders.

### Potential Solution

One potential solution would be to implement a visual workflow editor where users can define stages, transitions, and actions. This editor could allow for drag-and-drop functionality to create workflows, specify conditions (e.g., task status changes), and define actions (e.g., sending notifications, updating fields).

### Additional Context

This feature would significantly streamline our project management process, reduce errors, and improve overall efficiency. It would also ensure consistency in how tasks are handled across different projects and teams within our organization. Integrating this capability into our existing project management software would enhance its utility and make it a more powerful tool for managing complex projects effectively.

**Comment by thevijayshankersharma** [comment]
@singhJasvinder101 could you give level 3 label for this cause there will be 4 to 5 workflows in it.

**Comment by thevijayshankersharma** [comment]
Could you confirm once again what you set the name ?

**Comment by singhJasvinder101** [comment]
MY_REPO_ACCESS_TOKEN

**Comment by thevijayshankersharma** [comment]
did you done like this 
Navigate to Settings → Secrets → New repository secret.
Name the secret MY_REPO_ACCESS_TOKEN

cause the greeting message didn't showed up when i raise this issue.

**Comment by singhJasvinder101** [comment]
[screen-capture.webm](https://github.com/singhJasvinder101/MyBlog/assets/131908922/2f601a1b-a124-4816-84e1-7607c3d14f71)

**Comment by thevijayshankersharma** [comment]
I think we should use GTHUB_TOKEN only.

**Comment by singhJasvinder101** [comment]
Yes but I am not able to add it in environment that's why my own workflow is also not working.

**Comment by thevijayshankersharma** [comment]
i am reverting my previous PR and will check one again

**Comment by thevijayshankersharma** [comment]
should I raise an dummy issue to check if its working or not.

**Comment by singhJasvinder101** [comment]
Okayy
