### ISSUE TITLE
Adding a Alerting  popup

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [singhJasvinder101/MyBlog#11]
I think it is needed to add some alert about any wrong thing happened by the user in the login and signup page like when i am clicking the submit button without entering any field so it must show any warning .

https://github.com/singhJasvinder101/MyBlog/assets/118350936/0c9182e7-870d-449a-9279-325b582958cc

**Comment by singhJasvinder101** [comment]
are you doing this work ?

**Comment by Ayushmaanagarwal1211** [comment]
Yes i am working i will send pr today i want know to know which feature do you want like the red text that you used for email and pass validation or a new generated pop that will be shown to the right top corner of the screen

**Comment by singhJasvinder101** [comment]
show the errors in red text for both login and signup

1) make the validations on email and password, password(according to the backend validations same in frontend)
2) if the empty fields then also show error
