### ISSUE TITLE
[FEATURE] dummy issue 

### ISSUE THREAD

**Issue by thevijayshankersharma** [singhJasvinder101/MyBlog#112]
### Feature Description

na

### Use Case

na

### Potential Solution

na

**Comment by singhJasvinder101** [comment]
Not worked

**Comment by thevijayshankersharma** [comment]
Its because i have raised the issues earlier too

**Comment by singhJasvinder101** [comment]
Ohh!! wait let me try from another account

**Comment by thevijayshankersharma** [comment]
or should I add for every issue opened. It will be more good to.

**Comment by singhJasvinder101** [comment]
I have made dummy issue #113 with another account not worked there also

**Comment by thevijayshankersharma** [comment]
![image](https://github.com/singhJasvinder101/MyBlog/assets/109781385/0526580e-d3fc-43eb-8754-3b2caae6a929)

**Comment by thevijayshankersharma** [comment]
I have raised other PR check it once. It will send the comment regardless of first contribution or not.
