### ISSUE TITLE
[FEATURE]  add hover effect to blog articles

### ISSUE THREAD

**Issue by siddhant-2002** [singhJasvinder101/MyBlog#119]
### Feature Description

on hover divs will pop up with neon lights on border

### Use Case

on hover divs will pop up with neon lights on border

### Potential Solution

on hover divs will pop up with neon lights on border

### Additional Context

![image](https://github.com/singhJasvinder101/MyBlog/assets/112260375/b4c2c760-d9ad-44dd-9b6c-fdfef016f486)

**Comment by singhJasvinder101** [comment]
glowing cards are looking good but these cards will look weird on adding neon hover effects. So we are not planning to add it.

**Comment by siddhant-2002** [comment]
can we add only border and some zoom effect rather than neon?
