### ISSUE TITLE
Adding Interactive Hover effects to the items of the navigation bar 

### ISSUE THREAD

**Issue by Devaki01** [singhJasvinder101/MyBlog#12]
Hi @singhJasvinder101 ,

### Description of the issue
I would like to contribute by adding hover effects to the links in the navbar. This would highly increase interactivity and improve user experience.

### About Me 
Hello, my name is Devaki Joshi. I am a tech-enthusiast, specially passionate about front-end technologies such as React. As a GGSoC'24 contributor, I am really eager to make the proposed contributions and looking forward to learn more in the process.

**Comment by singhJasvinder101** [comment]
You can add style now

**Comment by Devaki01** [comment]
Thank you. Could you please assign it to me under ggsoc and add the label as well please

**Comment by singhJasvinder101** [comment]
have you completed work ??

**Comment by Devaki01** [comment]
hello actually I have an exam tomorrow. Will you please give me a day's time, I'll surely complete it by tomorrow evening.

**Comment by singhJasvinder101** [comment]
Okay

**Comment by Devaki01** [comment]
Actually I am having issue in setting up the project in my system. I have contacted a mentor having received a reply as of now. 
Will you please guide me through setting up of the backend of the project?

**Comment by Devaki01** [comment]
oh, I had contacted Sourav mishra. I sent a mail after which i was instructed to connect on discord but didn't receive any further updates after that.
And thank you so much for the help and extremely sorry for the delay.

**Comment by singhJasvinder101** [comment]
are you working on the issue ??
