### ISSUE TITLE
[BUG] Navbar is not sticky

### ISSUE THREAD

**Issue by the-code-artist** [singhJasvinder101/MyBlog#130]
### Bug Description

Nabar is not sticky which is making it difficult to navigate through other pages from anywhere in the present page
we cant access navbar from anywhere in the page which is effecting the user experience

### Steps to Reproduce

1. update css of navbar such that it sticky to the top of page
2. set its z-index to higher values such that it is not overlapped by any other components

### Expected Behavior

Navbar should be sticky and should stay on top

### Additional Context

hey @singhJasvinder101 
I am interested in resolving this bug and contribute it to the project
please do assign me this issue under GSSOC'24!!

**Comment by singhJasvinder101** [comment]
we are not expecting the sticky navbar. Thanks for the suggestion you can contribute to other issues.
