### ISSUE TITLE
FIX card for Mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [singhJasvinder101/MyBlog#131]
### Feature Description

The card sizing is not proper for mobile screen

### Use Case

I will make the website look professional

![image](https://github.com/singhJasvinder101/MyBlog/assets/124615886/90b3a8c6-18c3-473a-9a75-4c4d4091f619)

### Potential Solution

I will fix the card padding and sizing to have a proper uniform view

### Additional Context

I would love to contribute to this project

**Comment by singhJasvinder101** [comment]
Please check the issue if it's noot already exist then create new one.
you can work on the similar issue #127
