### ISSUE TITLE
Footer overlaps page content

### ISSUE THREAD

**Issue by Utsavladia** [singhJasvinder101/MyBlog#132]
### Feature Description

the footer is overlapping the content 

### Use Case

It should have proper sizing to have a better experience

![image](https://github.com/singhJasvinder101/MyBlog/assets/124615886/3eeca36c-623c-4ad1-b2c1-59ae7dfd5dba)

### Potential Solution

I would fix the sizing and padding to have a uniform look

**Comment by singhJasvinder101** [comment]
Issue is similar to #118 you can work on this issue there.
