### ISSUE TITLE
Issue with Text Overflow on Home Page Cards

### ISSUE THREAD

**Issue by deepak00944** [singhJasvinder101/MyBlog#133]
### Bug Description

I noticed an issue while browsing your website. The text on the cards featured on the homepage is overflowing beyond the card boundaries. This issue affects the visual appearance and readability of the content, and I recommend addressing it to improve user experience.

### Steps to Reproduce

We can directly see on home page attaching screenshots here.

### Expected Behavior

The text within the cards on the homepage should remain contained within the card boundaries. The content should be fully readable and neatly formatted, ensuring that no text overflows or spills outside the designated card area. This will maintain a clean and professional appearance and enhance the overall user experience.

### Screenshots

![image](https://github.com/singhJasvinder101/MyBlog/assets/119965267/efe1ec9b-dea9-4721-a140-52379fad638e)

![image](https://github.com/singhJasvinder101/MyBlog/assets/119965267/23422f5f-941f-4f95-a1dd-ca2b88b6131e)

### Desktop Information

Browser

**Comment by singhJasvinder101** [comment]
Please check the issue if it's noot already exist then create new one.
you can work on the similar issue #127

**Comment by deepak00944** [comment]
@singhJasvinder101 there is one similar issue which you have mentioned here if you allow me i can start working for that

**Comment by deepak00944** [comment]
one more thing in the existing issue the problem is with every card but in my case the issue is with 2 card only

**Comment by singhJasvinder101** [comment]
you need to make sure responsive in all devices by inspecting in browser. It's the generic problem so I redirected to that issue.

**Comment by deepak00944** [comment]
I am ready to work on it and I will give my best to make it responsive if you assign me this issue.

**Comment by RushilJalal** [comment]
Why is this issue closed? The issue still exists...

**Comment by deepak00944** [comment]
@singhJasvinder101 it is not running it gave some error i tried to solve still not running. (error for first time, Uncaught FirebaseError: Installations: Missing App configuration value: "apiKey" (installations/missing-app-config-values), Uncaught FirebaseError: Installations: Missing App configuration value: "projectId")

**Comment by RushilJalal** [comment]
@deepak00944 Well, the error says what the problem is. 
When you clone the website, I'm pretty sure you cannot access the Firebase `apiKey` since it's a secret.
To make it work on your local device, you need to configure another Firebase project from your own account.

**Comment by deepak00944** [comment]
Okay
