### ISSUE TITLE
[FEATURE] : Add hover effect and icon to  navbar 

### ISSUE THREAD

**Issue by Deepanshi-05** [singhJasvinder101/MyBlog#137]
### Feature Description

We need to enhance the user interface of our navigation bar by adding a hover effect and incorporating icons for each navigation item. This will improve the overall user experience and make the navigation more intuitive and visually appealing.

### Use Case

Improved User Experience on Desktop
 Enhanced Mobile Navigation
Accessibility Improvements
Consistent Brand Identity

### Potential Solution

Hover Effect:  Apply a smooth hover effect to each navigation item. The hover effect should change the background color and text color of the navigation item. The hover transition should be smooth and take around 0.3 seconds. Icons:  Add an icon to the left of the text for each navigation item. Use a consistent set of icons (e.g., FontAwesome, Material Icons) to ensure visual coherence. Ensure that the icons are appropriately sized and aligned with the text.

**Comment by GitNinja-bcd** [comment]
Kindly assign me this issue under GSSOC'24

**Comment by Pritam1729** [comment]
can i work on this issue under GSSOC 24
