### ISSUE TITLE
Improving Readme.md file 

### ISSUE THREAD

**Issue by RajatAgrawal117** [singhJasvinder101/MyBlog#14]
Improving the readme file with intructions to run the web app locally on the computer. Can you assign this to me under GSSOC 24?

**Comment by singhJasvinder101** [comment]
are you working in this issue ?

**Comment by aasthakourav20** [comment]
Hey @singhJasvinder101 , Please assign this issue to me under GSSoC'24

**Comment by singhJasvinder101** [comment]
Readme must catchy and attractive for the new contributors to join. It must contain each and every features of the blog site and the technologies , starred badges and more creative you can add by your own.
At last show all the contributors in the badges and shotout heading
