### ISSUE TITLE
[BUG] Comments section doesn't work

### ISSUE THREAD

**Issue by RushilJalal** [singhJasvinder101/MyBlog#143]
### Bug Description

On adding a comment, nothing happens

### Steps to Reproduce

1. Open the website at https://tech-stuffs.netlify.app/
2. Open any blogpost
3. Write and submit a comment. 
4. Notice that nothing happens and comment is not added.

### Expected Behavior

I expect the comment to be added and comment count to become +1

### Screenshots

![image](https://github.com/singhJasvinder101/MyBlog/assets/54212357/8e6a067c-fa3a-47cc-8af9-537870516170)

### Desktop Information

Windows 11, Chrome

### Additional Context

Can I contribute on this issue?

**Comment by singhJasvinder101** [comment]
google auth not working currently try by manual auth
