### ISSUE TITLE
[BUG] Search button not working

### ISSUE THREAD

**Issue by shravanibhor** [singhJasvinder101/MyBlog#144]
### Bug Description

Search Icon when clicked the + option doesnt work if not logged in

### Steps to Reproduce

1. Click the + on the bottom right [Shouldn't be logged in ]
2. Click on the search option

### Expected Behavior

Either the icon shouldn't be there or give the access of search function to the user without logging in

### Screenshots

![Screenshot (568)](https://github.com/singhJasvinder101/MyBlog/assets/121655392/e7f9be65-0798-4dc9-be99-92e8a80882a8)

**Comment by singhJasvinder101** [comment]
it will show after login
