### ISSUE TITLE
[BUG] Navbar links not responsive

### ISSUE THREAD

**Issue by me-nilakshi** [singhJasvinder101/MyBlog#154]
### Bug Description

When a new user, the navbar links are showing different responses.

### Steps to Reproduce

https://github.com/singhJasvinder101/MyBlog/assets/101091762/b0ee70aa-febc-41bd-9131-700a45d1c8b2

### Expected Behavior

For a new user, on clicking the navbar links, it displays the message that "You need to login to access these"

### Additional Context

I am a GSSoC' 24 contributor. Please assign this issue to me, I ensure to complete this within the given timeframe.

**Comment by adinathraut** [comment]
@singhJasvinder101 I worked on it kondly assign it to me under gssoc24
