### ISSUE TITLE
[BUG] Clicking on the blog card does not open blog

### ISSUE THREAD

**Issue by haseebzaki-07** [singhJasvinder101/MyBlog#168]
### Bug Description

on clicking on the blog card does not open blog instead shows a blank screen

### Steps to Reproduce

1. Go to Home Page
2. Click on any blog card.
3. Does not open blog instead shows blank screen
4. Ideally shoul open the blog page

### Expected Behavior

On clicking the blog card should open the blog page

### Screenshots

![Screenshot 2024-07-29 233904](https://github.com/user-attachments/assets/e31b8cea-17a6-4747-b6a3-b92c1c515454)

**Comment by abhishekshivgan** [comment]
@Saurabh-Rana17 can you help me set up the project locally. I am facing issues.

**Comment by singhJasvinder101** [comment]
> @Saurabh-Rana17 can you help me set up the project locally. I am facing issues.

you can see instructions in readme.md
