### ISSUE TITLE
[BUG] icon hides the footer content 

### ISSUE THREAD

**Issue by kapilG0** [singhJasvinder101/MyBlog#169]
### Bug Description

Icon hide footer 

### Steps to Reproduce

![Screenshot_20240807_175440](https://github.com/user-attachments/assets/50fe93a0-d571-4b00-ae9e-f1d892de940f)

### Expected Behavior

Icon should not hide footer

**Comment by kapilG0** [comment]
Hello @singhJasvinder101 please assign this issue to me under gssoc 24

**Comment by abhishekshivgan** [comment]
@kapilG0 @singhJasvinder101 can you help me setting up the project locally?
