### ISSUE TITLE
feat : Adding a smooth hovering animation on the cards .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [singhJasvinder101/MyBlog#21]
Adding a smooth pop out animation on hovering on the card to different from the other unfocused cards .

![Screenshot 2024-05-28 202404](https://github.com/singhJasvinder101/MyBlog/assets/118350936/b404a6b9-6e3a-44d7-afea-6f02b75a0be2)

**Comment by singhJasvinder101** [comment]
You can work on it and can create new issue for backend validation

**Comment by Ayushmaanagarwal1211** [comment]
Ok
