### ISSUE TITLE
user verify is not proper

### ISSUE THREAD

**Issue by Varsani2520** [singhJasvinder101/MyBlog#22]
@singhJasvinder101 ,
when i register on myBlog ,then it will directly redirect me to home page without login 

we have to firrst go to `/login` page and check user email and password based on that we redirect them to home and login success

**Comment by GuptaKap** [comment]
please assign me this task i have already work on that.

**Comment by singhJasvinder101** [comment]
No need of this functionality instead email verification will be much better
