### ISSUE TITLE
add image

### ISSUE THREAD

**Issue by Varsani2520** [singhJasvinder101/MyBlog#23]
its look cool if we add the some image otherwise web look like a boring :
![image](https://github.com/singhJasvinder101/MyBlog/assets/137641079/3ea4cf83-2a27-4327-9dab-53d576bb4781)
@singhJasvinder101

**Comment by Varsani2520** [comment]
Hey @singhJasvinder101 ,please add the label

**Comment by singhJasvinder101** [comment]
under the seeders folder run the seeder.js file

**Comment by Varsani2520** [comment]
i want to url for all the blog ,
in seeder file no url or url is present into .env file ,i have no access of env file:

this is seeder.js file:
![image](https://github.com/singhJasvinder101/MyBlog/assets/137641079/3b2b7c65-0e96-40bd-b5b4-2a4e958009ad)

**Comment by singhJasvinder101** [comment]
env files are not publically available, you need to add your own configurations

**Comment by Varsani2520** [comment]
Okay
