### ISSUE TITLE
Update the twitter (X) icon

### ISSUE THREAD

**Issue by swetha5157** [singhJasvinder101/MyBlog#27]
In the MyBlog website, the X icon has former twitter icon
Hence kindly assign this issue to me @swetha5157 under gssoc'24 and add level labels.
![Screenshot_20240529_165500_Chrome](https://github.com/singhJasvinder101/MyBlog/assets/123291594/31369fb6-f0b3-415a-a5cf-ae20bfc42505)

I abide by the Code of Conduct and Community Guidelines.

**Comment by singhJasvinder101** [comment]
I am closing this issue as its similar with #76
