### ISSUE TITLE
[FEAT]: Improving UI of the Blogs cards

### ISSUE THREAD

**Issue by aryansharma220** [singhJasvinder101/MyBlog#44]
The blogs cards are not very attractive to look at we can add some styling and also we can add borders to the blogs.
We should also add to the title which page blogs are we seeing since all the pages looks the same.

![image](https://github.com/singhJasvinder101/MyBlog/assets/133234867/0424be7d-e255-4270-8b1b-af4a72c4c52d)

Please assign it to me under gssoc24 so that I can work on it if you like the idea.

**Comment by aryansharma220** [comment]
@singhJasvinder101 Can you please provide the api_url so that i can fetch the blogs

**Comment by singhJasvinder101** [comment]
run seeder.js file in seeder folder

**Comment by singhJasvinder101** [comment]
@aryansharma220 you can add labels below the posts with random colours text
here is example you can refer to show coloured tags
![image](https://github.com/singhJasvinder101/MyBlog/assets/131908922/0c179514-7a47-4f17-8d8d-4c504e33c9b6)

https://dev.to/hoverbaum/how-to-add-code-highlighting-to-your-devto-posts-2lp6

**Comment by singhJasvinder101** [comment]
You can work on #105 closing this one.
