### ISSUE TITLE
Implement Google Signup Functionality

### ISSUE THREAD

**Issue by srivastav2006** [singhJasvinder101/MyBlog#45]
Users should be able to sign up using their Google tokens for authentication.

This feature enhances user convenience by allowing them to sign up using their Google accounts, reducing the need to remember additional login credentials.

actual:
![image](https://github.com/singhJasvinder101/MyBlog/assets/143505484/befd19c7-688c-4682-8d16-05a35ae6692f)
expected:
![Screenshot 2024-05-31 124841](https://github.com/singhJasvinder101/MyBlog/assets/143505484/9abe440f-73ad-443b-8721-aafc3b571928)

**Comment by singhJasvinder101** [comment]
are you working on the issue

**Comment by srivastav2006** [comment]
Yes, I need to talk to you regarding this. Can i get your discord id?

**Comment by drick-infinity** [comment]
can to assign this issue to me

**Comment by srivastav2006** [comment]
I can work on this issue. I just want to tell ,I will store my own firebase config as environment variable, and if everything is perfect the PA can replace it with his own, while hosting....

**Comment by singhJasvinder101** [comment]
Okay, you can work on the feature we will add the environment vars
