### ISSUE TITLE
Enhance footer  

### ISSUE THREAD

**Issue by aasthakourav20** [singhJasvinder101/MyBlog#48]
Adding Home , Services , About us , Blogs , FAQs section to the footer will make it user friendly &  enhanced footer functionality .
It will describe the project in better way .

**Comment by riyasaxena32** [comment]
I am interested in resolving issue for GSSoC '24 and believe my skills in make me a good fit. Please assign it to me.

**Comment by singhJasvinder101** [comment]
You can work on #105 closing this one.
