### ISSUE TITLE
Scroll progressbar missing

### ISSUE THREAD

**Issue by paulkrishanu4** [singhJasvinder101/MyBlog#53]
want to add scroll progressbar like this 

https://github.com/singhJasvinder101/MyBlog/assets/169196836/71c38b58-f06d-4cc1-a6ec-7f1c0762576e

**Comment by riyasaxena32** [comment]
I am interested in resolving issue for GSSoC '24 and believe my skills in make me a good fit. Please assign it to me.

**Comment by singhJasvinder101** [comment]
The progress bar length must be around 1-2 px only

**Comment by paulkrishanu4** [comment]
@singhJasvinder101 site is not opening in localhost showing multiple errors


<img width="960" alt="image" src="https://github.com/singhJasvinder101/MyBlog/assets/169196836/327e46a4-335b-4a3e-9c42-d521e6d6f422">


<img width="960" alt="image" src="https://github.com/singhJasvinder101/MyBlog/assets/169196836/b26e998c-d9ce-4aec-bd08-3ca84931a721">


<img width="960" alt="image" src="https://github.com/singhJasvinder101/MyBlog/assets/169196836/8a519155-7f3a-4880-a916-8e78a24317b5">

**Comment by singhJasvinder101** [comment]
add your own configurations  in .env

**Comment by singhJasvinder101** [comment]
You can work on #105 closing this one.
