### ISSUE TITLE
Implement Cookie Based User session Handling

### ISSUE THREAD

**Issue by RithikaSundaram** [singhJasvinder101/MyBlog#54]
Cookie-based user session handling involves storing a session ID in a cookie on the client's browser when a user logs in. The server validates this session ID to manage user sessions, ensuring secure and personalized user experiences. Sessions are typically configured with expiration times and security attributes like HttpOnly and SameSite to enhance security. This approach allows for efficient user authentication and session management in web applications

**Comment by RithikaSundaram** [comment]
Please assign this issue to me

**Comment by singhJasvinder101** [comment]
cookie based authentication, authorization already present.
