### ISSUE TITLE
 Missing Email Validation in User Signup

### ISSUE THREAD

**Issue by RithikaSundaram** [singhJasvinder101/MyBlog#55]
The current user signup process lacks email validation, allowing invalid or improperly formatted email addresses to be accepted. This can lead to issues with user communication, account verification, and overall data integrity. Implementing proper email validation will ensure that only valid email addresses are accepted during the signup process, improving the reliability and security of the application.

**Comment by RithikaSundaram** [comment]
Please assign this issue to me

**Comment by singhJasvinder101** [comment]
Email validations already present
