### ISSUE TITLE
Fix the overall UI

### ISSUE THREAD

**Issue by aasthakourav20** [singhJasvinder101/MyBlog#56]
The present UI looks quite unattractive due to its uncoordinated styles , Card sizes are too much big & can see mismatched color combinations . Moreover I can see  the hover effect looks uneasy due to large size of the cards , can make it better.
Please assign this issue to me under GSSoC'24 
If you have  any other suggestions , then it's welcome .

**Comment by singhJasvinder101** [comment]
You can work on #105 closing this one.
