### ISSUE TITLE
Light mode and Dark mode Toggle button

### ISSUE THREAD

**Issue by Hemashree21** [singhJasvinder101/MyBlog#7]
I can work on making the website in light mode so that users can toggle between the mode of their choice.

@singhJasvinder101 can you please assign this to me?

**Comment by Hemashree21** [comment]
Can you please add the level label as well?

**Comment by Hemashree21** [comment]
@singhJasvinder101 The .env file for the project is not there. can you please share it? I am not able to run the server without it.

![image](https://github.com/singhJasvinder101/MyBlog/assets/138188163/e371c5b2-04a2-465a-a571-299e86296962)

**Comment by singhJasvinder101** [comment]
@aryansharma220 help @Hemashree21 for basic setup of project

**Comment by aryansharma220** [comment]
@Hemashree21 you have to add a .env file in the backend folder and add your MONGO_URI there

**Comment by Hemashree21** [comment]
@aryansharma220 
![image](https://github.com/singhJasvinder101/MyBlog/assets/138188163/9bb67bf2-68ae-4d9e-9db8-8c37f6b33c9b)

Its showing like this

**Comment by aryansharma220** [comment]
> @aryansharma220 ![image](https://private-user-images.githubusercontent.com/138188163/335485961-9bb67bf2-68ae-4d9e-9db8-8c37f6b33c9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDE4NzAsIm5iZiI6MTcxNzE0MTU3MCwicGF0aCI6Ii8xMzgxODgxNjMvMzM1NDg1OTYxLTliYjY3YmYyLTY4YWUtNGQ5ZS05ZGI4LThjMzdmNmIzM2M5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNzQ2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWIzMTkyZTI0NWM3Y2Y2NDhkNDY2MjBmZTY0ZWI0MjE3MTQ0MTUxMDNmODkwMmM2NTliNzA4YWFhMzk2ZDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JhmRGcvyyrdfh15jjuq1cbINA56xmULr--5BtBiNmLc)
> 
> Its showing like this

You have to add your password at the placeholder in the URI <password> after your username

**Comment by Hemashree21** [comment]
> > @aryansharma220 ![image](https://private-user-images.githubusercontent.com/138188163/335485961-9bb67bf2-68ae-4d9e-9db8-8c37f6b33c9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDE4NzAsIm5iZiI6MTcxNzE0MTU3MCwicGF0aCI6Ii8xMzgxODgxNjMvMzM1NDg1OTYxLTliYjY3YmYyLTY4YWUtNGQ5ZS05ZGI4LThjMzdmNmIzM2M5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNzQ2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWIzMTkyZTI0NWM3Y2Y2NDhkNDY2MjBmZTY0ZWI0MjE3MTQ0MTUxMDNmODkwMmM2NTliNzA4YWFhMzk2ZDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JhmRGcvyyrdfh15jjuq1cbINA56xmULr--5BtBiNmLc)
> > Its showing like this
> 
> You have to add your password at the placeholder in the URI after your username

Yeah i know, I have set the password as password only, should I change it
