### ISSUE TITLE
Headers needs to be responsive after click on search

### ISSUE THREAD

**Issue by kapilG0** [singhJasvinder101/MyBlog#70]
![Screenshot_20240602_171723](https://github.com/singhJasvinder101/MyBlog/assets/59639410/f7abafa1-0392-44b8-b6d4-9796b08d2c6e)

**Comment by kapilG0** [comment]
Hello @singhJasvinder101 please assign this issue to me under gssoc 24

**Comment by kapilG0** [comment]
Hello @singhJasvinder101 i started to work on this issue but i am getting this now. as you assigned this to me i do not know who did that changes
![image](https://github.com/singhJasvinder101/MyBlog/assets/59639410/e71207d8-23bd-4d5b-8b58-0f202acd84e8)

**Comment by singhJasvinder101** [comment]
No issues @kapilG0 you can work on other issues or make other UI improvements. I am closing this issue now it has resolved now.
