### ISSUE TITLE
[DOC]: Adding Thanks to all contributors and support sections to README.

### ISSUE THREAD

**Issue by rithika212k3** [singhJasvinder101/MyBlog#75]
Hi @singhJasvinder101 ,

I would like to add the Thanks to Contributors section and the Support section to the README document to show love towards the contributors.
I have attached a Screenshot related to the same. **Can you please assign me this issue?**

![thanks_support](https://github.com/singhJasvinder101/MyBlog/assets/158501895/450d3644-ff98-4f56-bb63-abde472b2f13)

**Comment by singhJasvinder101** [comment]
the readme has already updated under #49
