### ISSUE TITLE
Enhancement: Replace twitter icon with X

### ISSUE THREAD

**Issue by AkhilaSunesh** [singhJasvinder101/MyBlog#76]
![image](https://github.com/singhJasvinder101/MyBlog/assets/140897461/b00bebbe-abe9-47b4-9d20-1cc39f67eb6f)
Replace twitter icon with X
Kindly assign this issue to me.

**Comment by riyasaxena32** [comment]
I am interested in resolving issue for GSSoC '24 and believe my skills in make me a good fit. Please assign it to me.

**Comment by riyasaxena32** [comment]
thnx i will resolve in 2 days

**Comment by singhJasvinder101** [comment]
You can work on #105 closing this one.
