### ISSUE TITLE
Elegant Light Theme

### ISSUE THREAD

**Issue by ShampaShaw** [singhJasvinder101/MyBlog#77]
the need for a light mode theme, such as improving readability in well-lit environments and providing an alternative to dark mode for users who prefer lighter interfaces

**Comment by riyasaxena32** [comment]
I am interested in resolving issue for GSSoC '24 and believe my skills in make me a good fit. Please assign it to me.

**Comment by singhJasvinder101** [comment]
you can work on it but the UI must be good.

**Comment by ShampaShaw** [comment]
I'm working on it is it is completed
