### ISSUE TITLE
[FEATURE]: Enhance footer. 

### ISSUE THREAD

**Issue by soniya-malviy** [singhJasvinder101/MyBlog#81]
### Feature Description

In footer right logo is not visible properly.

### Use Case

To enhance user experience and proper visibility of logo.

![Image 04-06-24 at 12 38 AM](https://github.com/singhJasvinder101/MyBlog/assets/151515611/8443960d-0e1b-47e5-a9bb-4f6f7bb4ceb2)

### Potential Solution

Add style to solve this.

**Comment by singhJasvinder101** [comment]
Thanks @soniya-malviy for suggestion but we are expecting another button for scroll to top above of it. So can't change its position

**Comment by soniya-malviy** [comment]
It’s fine @singhJasvinder101 we can set logo just above reserved text section and scroll button to as it is.It will look.

for example this 

![Image 03-06-24 at 3 49 PM](https://github.com/singhJasvinder101/MyBlog/assets/151515611/42408c4e-c1fc-4543-bb92-70e083fd8a68)


I maked this changes.In some other project.

**Comment by singhJasvinder101** [comment]
Okay you can work on this issue
