### ISSUE TITLE
[FEATURE] : google auth in login page

### ISSUE THREAD

**Issue by drick-infinity** [singhJasvinder101/MyBlog#84]
### Feature Description

there is option by which user can sign in via google for this website

### Use Case

on clicking this you can go to page via google sign 

### Potential Solution

using google Oauth feature 

### Additional Context

assign under gssoc'24 level3
![Screenshot (102)](https://github.com/singhJasvinder101/MyBlog/assets/116994649/e634263c-19b1-48fa-9cfa-0b4aeecaefd0)

**Comment by singhJasvinder101** [comment]
google auth added already
