### ISSUE TITLE
Fix Navbar at top to use it from anywhere in the website.

### ISSUE THREAD

**Issue by Utsavladia** [singhJasvinder101/MyBlog#85]
### Feature Description

Fix Navbar at top

### Use Case

Use it from anywhere in the website.

![image](https://github.com/singhJasvinder101/MyBlog/assets/124615886/4a1eb7b3-fce1-4fdb-aad7-60c9c9a87861)

### Potential Solution

Fix at top

**Comment by bhaskar-2024** [comment]
assign this to me please @Utsavladia

**Comment by Utsavladia** [comment]
@bhaskar-2024  bruh I already wanna work on it under GSSOC.
and I cannot assign anyone they will assign me.

**Comment by singhJasvinder101** [comment]
You can work on #105 closing this one.
