### ISSUE TITLE
[FEATURE] :overall ui of website

### ISSUE THREAD

**Issue by drick-infinity** [singhJasvinder101/MyBlog#87]
### Feature Description

onerall ui is not good need to enhance ui

### Use Case

its structure is totally distorted need a better ui 
assign under gssoc'24

### Potential Solution

i will design proper ui accordeing to this website by using tailwindcss and react components

**Comment by drick-infinity** [comment]
@singhJasvinder101  Thanks for assigning this issue to me ,As i learned MERN stack development I wants to contribte in ui designing of website can I get more information to your project Actually, I have an error when I deploy your project on my system I want to contribute in designing the ui of your web site but unable to get web site locally let me know about this so I further in contribution.
![Screenshot (119)](https://github.com/singhJasvinder101/MyBlog/assets/116994649/3c7f3e7b-52df-44c3-a015-f1d0e3738aa7)

**Comment by singhJasvinder101** [comment]
Add the .env configurations of your own you can take example from  .env.example file

**Comment by drick-infinity** [comment]
PORT=3000
BACKEND_URL=http://localhost:3000
CLIENT_URL=http://localhost:5173
DATABASE_URL=mongodb://username:password@localhost:27017/mydatabase
SESSION_SECRET=mySecret
i Use this but is not working
how can i proceed futher to designing of the website it just show the lo
![Screenshot (121)](https://github.com/singhJasvinder101/MyBlog/assets/116994649/041449d8-ec14-4c27-9ca1-2ef1fe7603b0)
ading screen

**Comment by singhJasvinder101** [comment]
You can work on #105 closing this one.
