### ISSUE TITLE
feat : Adding a password toggling eye in Login/SignUp page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [singhJasvinder101/MyBlog#9]
At the time of signin or login every user wants the password safe so if their is a feature of toggling the password with the eye icon whether to hide or show the password i think it will increase the UX of the user .

![Screenshot 2024-05-27 201909](https://github.com/singhJasvinder101/MyBlog/assets/118350936/60b53666-bdbf-44fa-981c-0c1df424103e)

**Comment by singhJasvinder101** [comment]
You can add now

**Comment by Ayushmaanagarwal1211** [comment]
Sure working on it !
