### ISSUE TITLE
[FEATURE] Enhance Website Interactivity with Animations

### ISSUE THREAD

**Issue by asthanegi14** [singhJasvinder101/MyBlog#92]
### Feature Description

I propose adding animations to the entire website to enhance user experience and interactivity. This enhancement will make the website more engaging and visually appealing, providing a smoother and more modern user interface.

### Use Case

Currently, the website provides static transitions between pages and interactions, which can feel abrupt and less engaging. We can improve Page Transitions, Button Clicks: Interactive button animations to provide feedback upon clicks, Hover Effects, and Loading Indicators.

### Potential Solution

Using built-in utility classes for transitions and animations of tailwind css

**Comment by asthanegi14** [comment]
Hey @singhJasvinder101
I want to work on this, assign this to me under GSSoC 2024.

**Comment by singhJasvinder101** [comment]
You can work on #105 closing this one.
