### ISSUE TITLE
[FEATURE]: Change Text Selection Color

### ISSUE THREAD

**Issue by SrinivasDevolper** [singhJasvinder101/MyBlog#96]
### Feature Description

Change Text Selection Color

### Use Case

Friendly-Experience

### Potential Solution

Change Text Selection Color

### Additional Context

![selction color change](https://github.com/singhJasvinder101/MyBlog/assets/121508628/c0c2d838-6752-4530-90b5-3dcb9763bf6a)

**Comment by singhJasvinder101** [comment]
You can work on #105 closing this one.
