### ISSUE TITLE
[FEATURE] : Adding some good hover effects in the navbar 

### ISSUE THREAD

**Issue by Rupalpy** [singhJasvinder101/MyBlog#97]
### Feature Description

Adding some good hover effects in the navbar , it makes it website more dynamic and fun to use .

### Use Case

This would address the issue of boring navigation links and hover effects , hover effect would make it more attractive .

### Potential Solution

Adding hover effects or maybe some animations.

**Comment by jayanththalla** [comment]
please assign me @singhJasvinder101 I will add the logo beside the title and hover the navbar

**Comment by singhJasvinder101** [comment]
You can work on #105 closing this one.
