### ISSUE TITLE
[BUG] Submit button camouflaging with the backgroud

### ISSUE THREAD

**Issue by Devaki01** [singhJasvinder101/MyBlog#98]
### Bug Description

The submit button in the login and sign up page is camouflaging with the background.

### Steps to Reproduce

1. Go to Log in / Sign up page.

### Expected Behavior

Submit button should be distinctly visible.

### Screenshots

<img width="659" alt="image" src="https://github.com/singhJasvinder101/MyBlog/assets/147143243/526244f0-1263-4800-b809-a3819b8e1e43">

### Additional Context

Please assign me this issue under gssoc'24.

**Comment by singhJasvinder101** [comment]
You can work on #105 closing this one.
